eligible_bachelors_collector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name = 'home'),
    path('about/', views.about, name = 'about'),    
    path('bachelors/', views.bachelors_index, name = "index"),
    path('bachelors/<int:bachelor_id>/', views.bachelors_detail, name = "detail"),
    path('bachelors/create/', views.BachelorCreate.as_view(), name = "bachelors_create"),
    path('bachelors/<int:pk>/delete/', views.BachelorDelete.as_view(), name = "bachelor_delete"),
    path('bachelors/<int:pk>/update/', views.BachelorUpdate.as_view(), name = "bachelor_update" ),
    path('bachelors/<int:bachelor_id>/add_prior_flame/', views.add_prior_flame, name = "add_prior_flame"),
    path('dealbreakers/', views.DealbreakerList.as_view(), name = "dealbreakers_index"),
    path('dealbreakers/create/', views.DealbreakerCreate.as_view(), name = "dealbreaker_create"),
    path('dealbreakers/<int:pk>/update/', views.DealbreakerUpdate.as_view(), name = "dealbreaker_update"),
    path('dealbreakers/<int:pk>/delete/', views.DealbreakerDelete.as_view(), name = "dealbreaker_delete"),
    path('bachelors/<int:bachelor_id>/assoc_db/<int:dealbreaker_id>/', views.assoc_db, name='assoc_db'),
    path('bachelors/<int:bachelor_id>/delete_db/<int:dealbreaker_id>/', views.delete_db, name='delete_db'), 
    path('bachelors/<int:bachelor_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Dealbreaker(models.Model):
    content = models.CharField(max_length = 100)

    def __str__(self):
        return self.content
    
    def get_absolute_url(self):
        return reverse('dealbreakers_index')

class Bachelor(models.Model): 
    name = models.CharField(max_length = 100)
    age = models.IntegerField()
    wealth_origin = models.TextField(max_length = 250)
    location = models.CharField(max_length = 100)
    net_worth = models.IntegerField()
    dealbreakers = models.ManyToManyField(Dealbreaker)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'bachelor_id': self.id})

class PriorFlame(models.Model):
    name = models.CharField(max_length = 100)
    age = models.IntegerField()
    relationship_duration = models.IntegerField('Together for (in months)')
    breakup_date = models.DateField('Breakup Date')
    bachelor = models.ForeignKey(Bachelor, on_delete=models.CASCADE)

    def __str__(self):
        return f"Don't sweat it! {self.bachelor.name} dumped {self.name} on {self.breakup_date}"
    
class Photo(models.Model):
    url = models.CharField(max_length=200)
    bachelor = models.ForeignKey(Bachelor, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for bachelor_id: {self.bachelor_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import PriorFlame

class PriorFlameForm(ModelForm):
    class Meta:
        model = PriorFlame
        fields = ['name', 'age', 'relationship_duration', 'breakup_date']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


import uuid
import boto3

from .models import Bachelor, PriorFlame, Dealbreaker, Photo
from .forms import PriorFlameForm

S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'eligiblebachelors'

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def bachelors_index(request):
    bachelors = Bachelor.objects.filter(user = request.user).order_by('-net_worth')
    return render(request, 'bachelors/index.html', {'bachelors': bachelors})

@login_required
def bachelors_detail(request, bachelor_id):
    bachelor = Bachelor.objects.get(id = bachelor_id)
    missing_dealbreakers = Dealbreaker.objects.exclude(id__in = bachelor.dealbreakers.all().values_list('id'))
    prior_flame_form = PriorFlameForm()
    return render(request, 'bachelors/details.html', {'bachelor': bachelor, 'prior_flame_form': prior_flame_form, 'dealbreakers': missing_dealbreakers})

@login_required
def add_prior_flame(request, bachelor_id):
    form = PriorFlameForm(request.POST)
    if form.is_valid():
        new_old_flame = form.save(commit=False)
        new_old_flame.bachelor_id = bachelor_id
        new_old_flame.save()
    return redirect('detail', bachelor_id = bachelor_id)
    
class BachelorCreate(LoginRequiredMixin, CreateView):
    model = Bachelor
    fields = '__all__'

    def form_valid(self, form):
    # Assign the logged in user
        form.instance.user = self.request.user
    # Let the CreateView do its job as usual
        return super().form_valid(form)

class BachelorDelete(LoginRequiredMixin, DeleteView):
    model = Bachelor
    success_url: '/bachelors/'

class BachelorUpdate(LoginRequiredMixin, UpdateView):
    model = Bachelor
    fields = '__all__'

class DealbreakerList(LoginRequiredMixin, ListView):
    model = Dealbreaker

class DealbreakerCreate(LoginRequiredMixin, CreateView):
    model = Dealbreaker
    fields = '__all__'

class DealbreakerUpdate(LoginRequiredMixin, UpdateView):
    model = Dealbreaker
    fields = ['content']

class DealbreakerDelete(LoginRequiredMixin, DeleteView):
    model = Dealbreaker
    success_url = '/dealbreakers/'

@login_required
def assoc_db(request, bachelor_id, dealbreaker_id):
    Bachelor.objects.get(id=bachelor_id).dealbreakers.add(dealbreaker_id)
    return redirect('detail', bachelor_id = bachelor_id)

@login_required
def delete_db(request, bachelor_id, dealbreaker_id):
    Bachelor.objects.get(id=bachelor_id).dealbreakers.remove(dealbreaker_id)
    return redirect('detail', bachelor_id = bachelor_id)

@login_required
def add_photo(request, bachelor_id):
	# photo-file was the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, bachelor_id=bachelor_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', bachelor_id=bachelor_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid credentials - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>Here comes the financially stable groom! </h1>
<p>It can be tough out there, so let us help you find the wealthy man of your dreams</p>

{% endblock %}

main_app/templates/bachelors/details.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
<div class = "center-align">
        <h1>{{ bachelor.name }}</h1>
        <h3>Net Worth: ${{ bachelor.net_worth|intcomma }} </h3>
</div>

        {% for photo in bachelor.photo_set.all %}
        <div class = "row">
                <div class = "col s4">
                        <img class="responsive-img card-panel" src="{{photo.url}}">
                </div>
</div>
        {% empty %}
        <div class = "row">
                <div class = "col s6">
                        <div class="card-panel center-align">
                                No Photos Uploaded
                        </div>
                </div>
                <div class = "col s6">
                <form action="{% url 'add_photo' bachelor.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
                        {% csrf_token %}
                        <input type="file" name="photo-file">
                        <br><br>
                        <input type="submit" class="btn" value="Upload Photo">
                </form>
        {% endfor %}
        </div>
        </div>
        </div>
        <p><b>Age: </b>{{ bachelor.age }}</p>
        <p><b>Location: </b>{{ bachelor.location }}</p>
        <p><b>Where'd He Get That Money? </b>{{ bachelor.wealth_origin }}</p>
        <div class="card-action">
                <a class = "btn right" href="{% url 'bachelor_update' bachelor.id %}">Edit</a>
                <a class = "btn right" href="{% url 'bachelor_delete' bachelor.id %}">Delete</a>
        </div>
</div>
</div>
<br><br>
<div class = "row">
        <div class = "col s6">
        {% if bachelor.dealbreakers.count %}
                <h5>Watch out for these dealbreakers!!</h5>
                {% for dealbreaker in bachelor.dealbreakers.all %}
                <ul>
                        <li><a class = "btn" href="{% url 'delete_db' bachelor.id dealbreaker.id %}"> X </a> {{dealbreaker.content}}</li>
                </ul>
                {% endfor%}
        {% else %}
                <h5>No dealbreakers yet? Maybe he's perfect?</h5>
                <h6>Though you know what they say about too good to be true...</h6>
        {% endif %}
        </div>
        <div class = "col s4 offset-s2">
                {% if dealbreakers %}
                <h5 class = "center-align">Add a Dealbreaker?</h5>
                {% for dealbreaker in dealbreakers.all %}
                <div class="card">
                        <div class="card-content">
                                <p>{{dealbreaker.content}}</p>
                        </div>
                        <div class="card-action">
                                <form action="{% url 'assoc_db' bachelor.id dealbreaker.id %}" method="post">
                                {% csrf_token %}
                                    <button type="submit" class="btn">Sounds like him!</button>
                                </form>
                        </div>
                        </div>
                {% endfor %}
                {% endif %}
                </div>
        </div>
</div>
<div class = "row">
<h5 class = "center-align">Are you his type? Check out these former flames!</h5>
<br>
<div class = "col s4 form">
        <form  action="{% url 'add_prior_flame' bachelor.id %}" method="POST">  
        {% csrf_token %}
        <h6 class = "heading">Add a New Old Flame</h6>
                {{ prior_flame_form.as_table }}
                <input type="submit" class="btn" value="Bye Bye B****">
        </form>
</div>
{% if bachelor.priorflame_set.all %}
        <div class = "col s6 offset-s2">
                <table>
                        <thead>
                                <tr>
                                <th>Name</th>
                                <th>Age</th>
                                <th>How long did it last?</th>
                                <th>When did it end?</th>
                                </tr>
                        </thead>
              
                        <tbody>
                        {% for pf in bachelor.priorflame_set.all %}
                                <td>{{pf.name}}</td>
                                <td>{{pf.age}}</td>
                                {% if pf.relationship_duration == 0%}
                                        <td>Nothing to worry about. Not even a month!</td>
                                {% else %}
                                <td>{{pf.relationship_duration}} mo </td>
                                <td>{{pf.breakup_date.month}}/{{pf.breakup_date.year}}</td>
                                {% endif %}
                        </tbody>
                        {% endfor %}
               </table>
                     
        </div>
{% endif %}
</div>
<script>
        var dateEl = document.getElementById('id_breakup_date');
        M.Datepicker.init(dateEl, {
                format: 'yyyy-mm-dd',
                defaultDate: new Date(),
                setDefaultDate: true,
                autoClose: true
        });
</script>
{% endblock %}

main_app/templates/bachelors/index.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
<div class = container>
<h2>Check Out These Bachelors</h2>

{% for bachelor in bachelors %}
<div class =  "card">
    <div class = "card-content">
    <div class = "row">
        <div class = "col s4">
        {% for photo in bachelor.photo_set.all%}
        {% if forloop.last%}
        <img class="responsive-img card-panel" src="{{photo.url}}">
        </div>
        {% endif %}
        {% endfor %}
        <div class = "col s8">
            <h1 class = "card-title">{{ bachelor.name }}</h1>
            <h6>Age: {{bachelor.age}}</h6>
            <h3>Net Worth: ${{ bachelor.net_worth|intword}}</h3>
            <a class = "right" href = "{%url 'detail' bachelor.id%}">Could he be the one?</a>
        </div>
    </div>
    </div>
</div>
{% endfor %}
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Most Eligible Bachelors</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lobster+Two|Satisfy" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Eligible Bachelors</a></li>
                </ul>
                <ul class="right">
                    <li><a class = "link" href="/about">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a id = "red-flag" class = "link" href = "/dealbreakers">Dealbreakers!</a></li>
                    <li><a class = "link" href = "/dealbreakers/create">Add A Dealbreaker</a></li>
                    <li><a class = "link" href = "/bachelors/create">Add A Bachelor</a></li>
                    <li><a class = "link" href="/bachelors">View All Bachelors</a></li>
                    <li><a class = "link" href="{% url 'logout' %}">Log Out</a></li>
                    {% else %}
                    <li><a class = "link" href="{% url 'signup' %}">Sign Up</a></li>
                    <li><a class = "link" href="{% url 'login' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	<footer class="page-footer">
       <div class="right">All Rights Reserved, &copy; 2019 Here Comes the Financially Stable Groom &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Have you been looking for love in all the wrong places?</h1>
<h4>They say it's just as easy to fall in love with a rich man as it is with a poor one, so why not aim for rich?!</h4>
<br><br>
<h5>Search through our list of most eligible bachelors under the age of 35 and start your journey to love today!</h5>

{% endblock %}

main_app/templates/main_app/bachelor_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Uh oh!</h1>

  <h4>Are you sure you're ready to let {{bachelor.name }} go?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Cut him loose!" class="btn">
    <a href="{% url 'detail' bachelor.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/bachelor_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
    <h2>Need to make some changes?</h2>
{% else %}
    <h2>Add A Bachelor</h2>
    <p>If only getting him was as easy as adding his name to the list, huh?</p>
{% endif %}

<form action = "" method = "post">
    {% csrf_token %}
    <table>
        {{ form.as_p}}
    </table>
    <input type="submit" value="Get him girl!" class="btn">
</form>

{% endblock %}

main_app/templates/main_app/dealbreaker_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete this dealbreaker!</h1>

  <h4>Are you sure you want to delete this dealbreaker?</h4>
  <p>{{dealbreaker.content}}</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="It don't bother me!" class="btn">
    <a href="{% url 'dealbreakers_index'%}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/dealbreaker_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Wanna make some changes to this dealbreaker?</h1>
  {% else %}
    <h1>Have a new dealbreaker in mind?</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_p }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/dealbreaker_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Yikes! Some potential dealbreakers!!</h1>

{% for dealbreaker in dealbreaker_list %}
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ dealbreaker.content }}</span>
            {% if dealbreaker.bachelor_set.all %}
                {% for bachelor in dealbreaker.bacheloer_set.all %}
                <ul>
                    <li> {{ bachelor.name }}  </li>
                </ul>
                {% endfor %}
            {% endif %}
            <a href="{% url 'dealbreaker_update' dealbreaker.id %}">Edit</a>
            <a href="{% url 'dealbreaker_delete' dealbreaker.id %}">Delete</a>
        </div>
    </div>
{% endfor %}

{% endblock %}